Update dependencies
As is, this causes builds to fail with:
Failed to execute: Executing Ant script: wolifecycle.build.xml [build-woframework]: Failed to execute.: java.lang.NoSuchMethodError: org.apache.tools.ant.launch.Locator.fromJarURI(Ljava/lang/String;)Ljava/lang/String;